function mday_plots_all(day)

mday_plots(day,'sim')
mday_plots(day,'posmvpos')
mday_plots(day,'gyro_s')
mday_plots(day,'log_chf')
%mday_plots(day,'ash')
mday_plots(day,'surfmet')
%day_plots(day,'airraw')
mday_plots(day,'metpro')
mday_plots(day,'met_light')
mday_plots(day,'met_tsg')
mday_plots(day,'tsg')
