% sets parameters to read common bottle salinity/oxygen/nutrient sample
% data file formats generated by NOC NMF/MPOC or OBG.
% if relevant, put this at the top of your opt_{cruise}.m file, to be run
% after mexec_defaults_all.m and before the rest of the contents of
% opt_{cruise}.m

switch opt1

    case 'ctd_proc'
        switch opt2
            case 'minit'
                stn_string = sprintf('%03d',stn); %for file names
            case 'oxy_align'
                %name in raw file, name in 24 hz file (don't change the 2nd
                %column!)
                oxyvars = {'oxygen_sbe1', 'oxygen1'; 'oxygen_sbe2', 'oxygen2'};
                oxyunit = 'umol/kg';
            case 'redoctm'
            case '1hz_interp'
                maxfill24 = 0; maxfill1 = 2;
                %other steps

        end

    case 'ladcp_proc'
        min_nvmadcpprf = 3;      %throws a warning if number of vmADCP profiles within an LADCP cast is less than this
        min_nvmadcpbin = 3;      %masks depths with number of valid bins less than this
        min_nvmadcpbin_refl = 3; %throws a warning if number of good profiles at any depth in the watertrack reference layer is less than this
        spath = fullfile(mgetdir('M_LADCP'), 'ix', 'SADCP');
        sfile = fullfile(spath, sprintf('os75nb_%s_ctd_%03d_forladcp.mat',mcruise,stn));

    case 'samp_proc'
        switch opt2

            case 'files'
                switch samtyp
                    case 'oxy'
                        files = dir(fullfile(root_oxy,['oxy_' mcruise '_*.csv'])); %*** move to individual options files
                        sopts.hcpat = {'Bottle';'Number'}; %Flag is on 2nd line so start here
                        stops.icolhead = 1;
                        sopts.icolunits = 2;
                    case 'nut'
                        files = dir(fullfile(root_nut,'*.xlsx')); %***move to individual options files
                        files = cellfun(@(x,y) fullfile(x,y),{files.folder},{files.name},'UniformOutput',false);
                        sopts.hcpat = {'Nitrate+Nit'};
                        sopts.icolhead = 1; sopts.icolunits = 1; sopts.sheets = 1;
                        opt1 = 'samp_proc'; opt2 = 'files'; get_cropt
                    case 'sal'
                        sopts.DateLocale = "en_GB"; %***
                end

            case 'parse'
                clear varmap
                switch samtyp
                    case 'oxy'
                        calcoxy = 1; %calculate from titre vol etc.
                        %rename variables (if necessary)
                        varmap.statnum = {'cast_number'};
                        varmap.position = {'niskin_bottle'};
                        varmap.conc_o2 = {'c_o2_','c_o2'};
                        varmap.vol_blank = {'blank_titre'};
                        varmap.vol_std = {'std_vol'};
                        varmap.vol_titre_std = {'standard_titre'};
                        varmap.fix_temp = {'fixing_temp'};
                        varmap.oxy_bottle = {'bottle no'};
                        %varmap.sample_titre = {'sample_titre'};
                        varmap.date_titre = {'dnum'}; %***
                        varmap.bot_vol_tfix = {'botvol_at_tfix'};
                        keepothervars = 0; %after renaming, remove anything without an entry in varmap***
                    case 'nut'
                        cu = [1 0];
                        %parse to get sampnum, set flags, and change variable names
                        varmap.statnum = {'cast_number'};
                        varmap.position = {'niskin_bottle'};
                        varmap.totnit_per_l = {'nitrate_plus_nit','no3_plus_no2'};
                        varmap.nitrite_per_l = {'nitrite','no2'};
                        varmap.nitrate_per_l = {'nitrate','no3'};
                        varmap.silc_per_l = {'silicate'};
                        varmap.phos_per_l = {'phosphate'};
                        varmap.amon_per_l = {'ammonium'};
                        varmap.totnit_flag = {'flag'};
                        varmap.nitrate_flag = {'flag'};
                        varmap.nitrite_flag = {'flag'};
                        varmap.silc_flag = {'flag'};
                        varmap.phos_flag = {'flag'};
                        varmap.amon_flag = {'flag'};
                        keepothervars = 0; %after renaming, remove anything without an entry in varmap
                    case 'sal'
                        calcsal = 1; %calculate from cond ratio and temperature
                        keepothervars = 1; %keep original names by default
                end

            case 'calc'
                switch samtyp
                    case 'oxy'
                        labT = 25; %labT for bottle vol calibrations
                        vol_reag_tot = 2; %1ml manganese chloride + 1ml alkaline iodide -- modify based on dispensette calibration
                end

        end

end