matlist = {           
%        'adupos'              ' '  'ADUPOS-PAPOS.gps'
%        'adupos' ' '   'PASHRPOS-PAPOS.PASHR'
%        'adu5pat'       'gps_ash'  'gppat-GPPAT.att'
%        'adu5pat' ' '  'GPPAT-GPPAT.GPPAT'
%        'adu5pat'     ' '   'ADU2-ASH.gps'
 'cnav'         'cnav'             'cnav-CNAV-3050_GPS.GPS'
%        'gps_g12'       'gps_g12'  'ADUPOS-G12PAT.gps'
%        'gps4000' ' '   'position-4000.gps'
%        'gpsfugro' ' '   's9200G2s-FUGRO.GPS'
        'gpsfugro' 'cnav'   'cnav-FUGRO-SEASTAR_GPS.GPS'
        'posmvpos' 'posmvpos'   'position-POSMV_GPS.gps'
        'seapos' 'seapos' 'position-Seapath330_GPS.gps'
        'satinfoposmv' ' ' 'satelliteinfo-POSMV_GPS.gps'
        'satinfocnav' ' ' 'satelliteinfo-CNAV-3050_GPS.GPS'
        'satinfofugro' ' ' 'satelliteinfo-FUGRO-SEASTAR_GPS.GPS'
        'satinfosea' ' ' 'satelliteinfo-Seapath330_GPS.gps'
        'attposmv' 'attposmv' 'shipattitude-POSMV_ATT.att'
        'attposmvaux' 'attposmv' 'shipattitude_aux-POSMV_ATT.att'
        'attphins' ' ' 'shipattitude-Phins_ATT.att'
        'attphinsaux' ' ' 'shipattitude_aux-Phins_ATT.att'
        'attsea' 'attsea' 'shipattitude-Seapath330_ATT.att'
        'attseaaux' 'attsea' 'shipattitude_aux-Seapath330_ATT.att'
%        'gps1' ' ' 's9200G2s-GPS1.GPS' % di368 gps splitter test
%        'gps2' ' ' 's9200G2s-GPS2.GPS' % di368 gps splitter test
        'gyro' ' '   'gyro-POSMV_GYRO.gyr'
        'gyro_s' ' '   'gyro-SGYRO_GYRO.gyr'
        'satinfo4000' ' '   'satelliteinfo-4000.gps'
        'satinfofugro' ' '   'satelliteinfo-FUGRO.gps'
 'em120'        'em120'             'sb_depth-EM120_DEPTH.depth'
 'sim'       'sim'             'EA600-EA640_DEPTH.EA600'
 'envtemp'   ' '   'ENV_TEMP-ENV_TEMP.ENV_TEMP'
%        'ea600m'      ' '   'PES-Simrad.PES'
%        'log_chf'       'log_chf'  'DYLog-LOGCHF.DYLog'
%        'log_chf ' ' '   'EMLog-LOGCHF.EMLog'
%        'log_chf'     ' '   'logchf-log.logchf'
 'log_skip'     'log_skip'             'logskippervdvbw-SKIP_LOG.nc'
%         'SBE45' ' '  'SBE45-SBE45.TSG'
%          'SBE45'                   'SBE45'       'SBE45-SBE45_DY1.TSG'
        'surflight'     'surfmet'  'Light-SURFMET.SURFMETv2'
        'surflight'     'surfmet'  'Light-SURFMET.SURFMETv3'
%        'surflight' ' '  'Light-SURFMET.SURFMETv2'
%        'surfmet' ' ' 'MET-SURFMET.SURFMETv2'
        'surfmet' ' ' 'MET-SURFMET.SURFMETv3'
%        'surfmet'       'surfmet'  'MET-SURFMET.SURFMETv2'
        'surfmet'     ' '   'SURFMET-Surfmet.met'
        'surftsg'       'surfmet'  'Surf-SURFMET.SURFMETv2'
         'tsg'                   'tsg'                          'SBE45-SBE45.TSG'
%        'surftsg' ' '   'Surf-SURFMET.SURFMETv2'
 'met_tsg'      'surfmet'             'Surf-SURFMET.SURFMETv3'
%         'winch'           'winch'  'DWINCH-CLAM.DWINCH'
%        'winch'       ' '   'DWINCH-CLAM.DWINCH'
%        'winch' ' '   'CLAM-CLAM.CLAM'
        'winch' 'winch'   'CLAM-CLAM_WINCH.CLAM'
        'usbl'        ' '   'USBL-USBL01.usbl'
        'usbl'        ' '   'position-usbl_DY1.gps'
%        'wamos' ' ' 'wamos-WaMoS.nc'
};
