% apply towyo positions to 2db and 2up files
% positions generated by jc069_towyo_summary


mcd M_CTD

otfile1 = [MEXEC_G.MSCRIPT_CRUISE_STRING '_towyo_summary'];
otfile2 = [otfile1 '_downup_positions'];

cmd = ['dpos = load(''' otfile2 ''');']; eval(cmd)

numfiles = size(dpos,1);

for kf = 1:numfiles
    stn = dpos(kf,1);
    flag = dpos(kf,2);
    lat = dpos(kf,3);
    lon = dpos(kf,4);
    stn_string = sprintf('%03d',stn);
    clear stn % so it doesnt hang around at end of script
    prefix1 = ['ctd_' MEXEC_G.MSCRIPT_CRUISE_STRING '_'];

    infile1 = [prefix1 stn_string '_2db' ];
    infile2 = [prefix1 stn_string '_2up' ];
    
   switch flag
       case 1
           infile = infile1;
       case 2 
           infile = infile2;
       otherwise
           continue
   end
   mputpos(infile,lat,lon); % apply required position
end