function [udirs, udcruise] = m_udirs();

udcruise = 'jc211';
udirs = {
'hdtgyro'    'nav/gyro'    'ships_gyro_hehdt';
'winch'    'ctd/WINCH'    'nmf_winch_winch';
'hdtpmv'    'nav/pmv'    'posmv_gyro_gphdt';
'attpmv'    'nav/pmv'    'posmv_att_pashr';
'pospmv'    'nav/pmv'    'posmv_pos_gpgga';
'vtgpmv'    'nav/pmv'    'posmv_pos_gpvtg';
'surfmet'    'met/surfmet'    'nmf_surfmet_gpxsm';
'windsonic'    'met/sonic'    'windsonic_nmea_iimwv';
'poscnav'    'nav/cnav'    'cnav_gps_gngga';
'vtgcnav'    'nav/cnav'    'cnav_gps_gnvtg';
'dopcnav'    'nav/cnav'    'cnav_gps_gngsa';
'posdps'    'nav/dps'    'dps116_gps_gpgga';
'em120'    'bathy/em120'    'em120_depth_kidpt';
'ea600'    'bathy/ea600'    'em600_depth_sddbs';
'envtemp'    'uother/env'    'env_temp_wimta';
'envhumid'    'uother/env'    'env_temp_wimhu';
'posranger'    'nav/ranger'    'ranger2_usbl_gpgga';
'tsg'    'met/tsg'    'sbe45_tsg_nanan';
'hdtsea'    'nav/sea'    'seapath_pos_inhdt';
'possea'    'nav/sea'    'seapath_pos_ingga';
'dopsea'    'nav/sea'    'seapath_pos_ingsa';
'vtgsea'    'nav/sea'    'seapath_pos_invtg';
'attsea'    'nav/sea'    'seapath_att_psxn23';
'logchf'    'uother/chf'    'ships_chernikeef_vmvbw';
'logskip'    'uother/skip'    'ships_skipperlog_vdvbw';
'gravity'    'uother/gravity'    'u12_at1m_uw';
};
