function udirs = mtsdirs();

%nav streams
udirsn = {
     'adupos'              'nav/adu'
	 'adu5pat'             'nav/adu'
	 'ashtech'             'nav/ash'
	 'attsea'              'nav/seaatt'
	 'attseaaux'           'nav/seaatt'
     'attphins'            'nav/phinsatt'
     'attposmv'            'nav/posmvatt'
	 'cnav'                'nav/cnav'
	 'satinfocnav'         'nav/cnav'
	 'dps116'              'nav/dps'
     'posdps'              'nav/dps'
	 'satinfodps'          'nav/dps'
	 'dps116_regen'        'nav/dps'
	 'furuno_gga'          'nav/furuno'
	 'furuno_gll'          'nav/furuno'
	 'furuno_rmc'          'nav/furuno'
	 'furuno_vtg'          'nav/furuno'
	 'furuno_zda'          'nav/furuno'
	 'glonass'             'nav/glonass'
     'gps_g12'             'nav/gps'
	 'gps4000'             'nav/gps'
	 'satinfo4000'         'nav/gps'
	 'gpsfugro'            'nav/gps'
	 'satinfofugro'        'nav/gps'
	 'gps1'                'nav/gps'
	 'gps2'                'nav/gps'
     'gyropmv'             'nav/gyropmv'
	 'gyro_s'              'nav/gyros'
	 'posmvpos'            'nav/posmvpos'
	 'satinfoposmv'        'nav/posmvpos'
	 'posmvpos_regen'      'nav/posmvpos'
	 'posmvtss'            'nav/posmvtss'
	 'seapos'              'nav/seapos'
	 'satinfosea'          'nav/seapos'
     'posranger'           'nav/ranger'
     'satinforanger'       'nav/ranger'
	 'seapos_regen'        'nav/seapos'
	 'seatex_gga'          'nav/seatex'
	 'seatex_gll'          'nav/seatex'
	 'seatex_hdt'          'nav/seahead'
	 'seatex_psxn'         'nav/seatex'
	 'seatex_vtg'          'nav/seatex'
	 'seatex_zda'          'nav/seatex'
	 'tsshrp'	       'nav/tsshrp'
   	 'dopplerlog'      'nav/log'
	 'chf'             'nav/log'
	 'emlog_vlw'       'nav/log'
	 'emlog_vhw'       'nav/log'
	 'log_chf'         'nav/log'
	 'log_skip'        'nav/log'
        };

    %others
udirso = {
     'surflight'       'met/surflight'
	 'surflight_regen' 'met/surflight_regen'
     'met_light'       'met/surflight'
	 'surfmet'         'met/surfmet'
%	 'surfmet'         'met/anemom'
	 'anemometer'         'met/anemom'
	 'surfmet_regen'   'met/surfmet'
	 'met_tsg'         'ocl/tsg'
	 'surftsg'         'ocl/tsg'
	 'oceanlogger'     'ocl/tsg'
	 'ocl'             'ocl/tsg'
	 'SBE45'           'ocl/tsg'
	 'tsg'             'ocl/tsg'
%	 'surftsg'         'ocl/tsg'
	 'surftsg_regen'   'ocl/tsg'
	 'sim'             'bathy/sim'
	 'em120'           'bathy/em120'
	 'em122'           'bathy/em120'
	 'gravity'	       'uother/gravity'
	 'mag'		       'uother/mag'
	 'seaspy'	       'uother/mag'
	 'netmonitor'      'uother/netmonitor'
	 'usbpos'	       'uother/usbl'
	 'satinfousb'      'uother/usbl'
	 'usbl'		       'uother/usbl'
	 'usbl_gga'	       'uother/usbl'
	 'winch'	       'uother/winch'
        };

udirs = [udirsn; udirso]; clear udirsn udirso
