function msbe_02_edcal(stn)
% msbe_02_edcal(stn)
%
% load raw file generated by msbe_01_load, apply automatic edits and
% corrections from the list below where they have not already been applied
% (as determined from the file header), and user-supplied calibrations if
% available
%
% corrections (in order):
%   align
%   cell thermal mass
%   oxygen tau
%   oxygen hysteresis
%
% save as _24hz
%
% output: _raw_cleaned and _24hz
%
% calls:
%     
%     apply_autoedits
%     (optionally) apply_ctd_celltm
%     mfsave
%     apply_oxyhyst
%     apply_calibrations

%%%%% setup %%%%%

m_common; MEXEC_A.mprog = mfilename;
if MEXEC_G.quiet<=1; fprintf(1,'applying corrections/conversions (e.g. oxygen hysteresis), as set in get_cropt and opt_%s\n',mcruise); end

% input and output files
pd = mexec_file_locations('procfiles','ctd');
rawfile = sprintf(pd.ctdraw,stn_string);
cleanfile = m_add_nc(sprintf(pd.ctdclean,stn_string));
file24 = sprintf(pd.ctd24,stn_string);
edfilepre = sprintf(pd.edctd24, stn_string);
pd = mexec_file_locations('procfiles','dcs');
dfile = sprintf(pd.dcsfile,stn_string);

% start from the raw (cnv) file
[d, h] = mloadq(rawfile,'/');

% what steps have been done
doneco.oxytau = contains(h.comment, '# datcnv_ox_tau_correction = yes');
doneco.oxy1hyst = contains(h.comment, '# datcnv_ox_hysteresis_correction = yes');
doneco.oxy2hyst = doneco.oxy1hyst;
doneco.alignctd = contains(h.comment, '# alignctd_date');
doneco.celltm = contains(h.comment, '# celltm_date');
%***filtering? wildedit? 


% what corrections, edits, and calibrations will we do
opt1 = 'ctd_proc'; opt2 = 'raw_corrs'; get_cropt
opt1 = 'ctd_proc'; opt2 = 'rawedit_auto'; get_cropt
opt1 = 'ctd_proc'; opt2 = 'ctd_cals'; get_cropt


%%%% edit out bad points

%automatic edits
fn = setdiff(fieldnames(d),{'statnum','latitude','longitude','altimeter','scan','pumps','time'});
% for fno = 1:length(fn)
%     d.([fn{fno} '_flag']) = 2+zeros(size(d.scan));
%     h.fldnam = [h.fldnam [fn{fno} '_flag']];
%     h.fldunt = [h.fldunt 'woce'];
%     h.fldserial = [h.fldserial 'n/a'];
% end
[d, comment] = apply_autoedits(d, co);
if ~isempty(comment)
    h.comment = [h.comment comment];
    disp('applied automatic edits')
end

%reapply hand edits, adding a flag of 7 (despiked) where points are removed
[d, comment] = apply_guiedits(d, 'scan', edfilepre, 0.1);%, [2 7]);
if ~isempty(comment)
    h.comment = [h.comment comment];
    disp('re-applied manual edits')
end

%fill in some fields we may be missing
if ~isfield(d, 'statnum')
    d.statnum = repmat(stn, size(d.scan));
    h.fldnam = [h.fldnam 'statnum']; h.fldunt = [h.fldunt 'number'];
    h.fldserial = [h.fldserial 'n/a'];
end
ddu = ['days since ' num2str(MEXEC_G.MDEFAULT_DATA_TIME_ORIGIN(1)) '-01-01 00:00:00'];
d.dday = m_commontime(d,'time',h,ddu);
h.fldnam = [h.fldnam 'dday']; h.fldunt = [h.fldunt ddu]; h.fldserial = [h.fldserial ' '];


%%%%% apply corrections %%%%%

%pressure offset (deck pressure)
if co.dpoff_calc
    iid = 1:60*24;% first minute on deck
    %if max(d.press(iid))>0.3 %&& checked = [6 1]; ~checked(checked(:,1)==stnlocal)
        %keyboard
    %else
        co.dpoff = -median(d.press(iid),'omitnan');
        fprintf(1,'pre-cast p offset: %f\n',co.dpoff)
    %end
    d.press = d.press + co.dpoff;
    h.comment = [h.comment '\npressure offset by ' num2str(co.dpoff) ' dbar'];
    doneco.dpoff = 1;
end

%oxygen recalculation from V (with alternate temperature sensor). uncommon. 
if co.dooxy1V>0 && isfield(co,'oxy1Vcoefs')
    warning('be cautious with oxygen calculated with alternate temperature sensor')
    t = d.(['temp' num2str(co.dooxy1V)]);
    c = d.(['cond' num2str(co.dooxy1V)]);
    s = gsw_SP_from_C(c,t,d.press);
    d.oxy1 = calculate_oxy_from_V(d.sbeoxyV1, d.time, d.press, t, s, co.oxy1Vcoefs);
    h.comment = [h.comment '\n oxy1 recalculated from sbeoxyV1 using CTD' num2str(co.dooxy1V) ' '];
    doneco.oxy1hyst = 0;
else
    co.dooxy1V = 0;
end
if co.dooxy2V>0 && isfield(co,'oxy2Vcoefs')
    warning('be cautious with oxygen calculated with alternate temperature sensor')
    t = d.(['temp' num2str(co.dooxy2V)]);
    c = d.(['cond' num2str(co.dooxy2V)]);
    s = gsw_SP_from_C(c,t,d.press);
    d.oxy2 = calculate_oxy_from_V(d.sbeoxyV2, d.time, d.press, t, s, co.oxy2Vcoefs);
    h.comment = [h.comment '\n oxy2 recalculated from sbeoxyV2 using CTD' num2str(co.dooxy2V) ' '];
    doneco.oxy2hyst = 0;
else
    co.dooxy2V = 0;
end

%oxygen tau and hysteresis, including first reversing default hysteresis if
%required
if ~doneco.oxytau %is this likely to happen?***
end
if co.re_dooxyhyst
    %set up a new structure
    oco.H_0 = [co.hyst_oxy0.H1 co.hyst_oxy0.H2 co.hyst_oxy0.H3];
    if doneco.oxy1hyst
        %reverse first, then apply new
        oco.hrev_oxy1 = co.hyst_oxy0;
    end
    if doneco.oxy2hyst
        oco.hrev_oxy2 = co.hyst_oxy0;
    end
    if isfield(co,'hyst_oxy1')
        oco.hyst_oxy1 = co.hyst_oxy1;
    else
        oco.hyst_oxy1 = co.hyst_oxy0;
    end
    if isfield(co,'hyst_oxy2')
        oco.hyst_oxy2 = co.hyst_oxy2;
    else
        oco.hyst_oxy2 = co.hyst_oxy0;
    end
    [dnew, hnew] = apply_oxyhyst(d, h, oco);
    fn = fieldnames(dnew);
    for no = 1:length(fn)
        d.(fn{no}) = dnew.(fn{no});
        doneco.([fn{no} 'hyst']) = 1;
    end
    h.comment = [h.comment hnew.comment];
    disp('applied oxygen hysteresis')
elseif ~doneco.oxy1hyst
    warning('no oxygen hysteresis correction has been applied to %s',stn_string)
end

%alignment in time, for oxygen only
if ~doneco.alignctd
    if co.oxy_align>0 %sbe says between 3 and 7
        oxyvars = h.fldnam(strncmp(h.fldnam,'oxy',3));
        for no = 1:length(oxyvars)
            d.(oxyvars{no}) = interp1(d.time, d.(oxyvars{no}), d.time+co.oxy_align);
        end
        h.comment = [h.comment '\nalign: oxygen shifted by ' num2str(co.oxy_align) ' s'];
        doneco.alignctd = 1;
        disp('oxygen aligned')
    else
        warning('no oxygen alignment applied to %s',stn_string)
    end
end

%cell thermal mass
if ~doneco.celltm % | co.redoctm (do we have a way to undo or does this require going back to the .hex or pre-ctm .cnv file?)***
    d.cond1 = apply_ctd_celltm(d.time, d.temp1, d.cond1);
    d.cond2 = apply_ctd_celltm(d.time, d.temp2, d.cond2);
    h.comment = [h.comment '\n celltm: cond corrected for cell thermal mass by ctd_apply_celltm'];
    doneco.ctm = 1;
    disp('cellTM applied')
end

% turbidity conversion from turbidity volts
if co.doturbV
    d.turbidity = (d.turbidityV-co.turbVpars(2))*co.turbVpars(1);
    d = rmfield(d,'turbidityV');
    hnew.comment = [hnew.comment '\n turbidity converted from turbidity volts'];
    h.fldnam{strcmp('turbidityV',h.fldnam)} = 'turbidity';
    d = orderfields(d,h.fldnam);
end

%save record of corrections applied, so we don't have to parse it from the
%comment string each time
MEXEC_G.doneco(stnlocal) = doneco;

tic
%%%%% save as cleaned %%%%%
if exist(cleanfile,'file')
    delete(cleanfile)
end
mfsave(cleanfile, d, h);
toc

%%%%% user sensor calibrations (based on discrete sample data) %%%%%
if isfield(co, 'calstr') && sum(cell2mat(struct2cell(co.docal)))
    %apply calibrations
    [dcal, hcal] = apply_calibrations(d, h, co.calstr, co.docal, 'q');
    hcal = keep_hvatts(hcal, h);

    %if there were calibrations applied to any variables, save those to
    %24hz file (overwriting uncalibrated versions)
    if ~isempty(hcal.fldnam)
        d = dcal; h = hcal;
        mfsave(file24, d, h, '-addvars');
    end

else
    %just save to 24 hz file
    copyfile(cleanfile, file24);

end


%%%%% check and warn
opt1 = 'ctd_proc'; opt2 = 'cast_divide'; get_cropt
if exist(dfile,'file')
    [ddc,~] = mload(dfile,'/');
    m = d.scan>=ddc.scan_start & d.scan<=ddc.scan_end;
else
    m = true(size(d.scan));
end
if min(d.press(m))<=-3 && (~isfield(co,'badpress') || ((isfield(co,'badtemp1') || isfield(co,'badtemp2'))))
    msg = ['negative pressures in ' file24 ' may indicate you should apply a deck ' ...
        '\npressure offset and/or apply range editing, despiking, or hand edits to remove '...
        '\noutliers. if large spikes also affect temperature, you should reprocess this station,'...
        '\nloading data to which the cell thermal mass correction has not yet been applied, '...
        '\nso you can edit out T spikes before the correction is applied in this function'];
    sprintf(msg)
    k = input('k for keyboard or enter to continue   ','s');
    if strcmp(k,'k')
        keyboard
    end
end
