function msbe_02_edcal(stn)
% mctd_02(stn)
%
% load raw file generated by msbe_01_load, apply automatic edits and
% corrections from the list below where they have not already been applied
% (as determined from the file header), and user-supplied calibrations if
% available
%
% corrections (in order):
%   align
%   cell thermal mass
%   oxygen tau
%   oxygen hysteresis
%
% save as _24hz
%
% output: _raw_cleaned and _24hz
%
% calls:
%     
%     apply_autoedits
%     (optionally) apply_ctd_celltm
%     mfsave
%     apply_oxyhyst
%     apply_calibrations

%%%%% setup %%%%%

m_common; MEXEC_A.mprog = mfilename;
if MEXEC_G.quiet<=1; fprintf(1,'applying corrections/conversions (e.g. oxygen hysteresis), as set in get_cropt and opt_%s\n',mcruise); end

% input and output files
opt1 = 'ctd_proc'; opt2 = 'ctdfiles'; get_cropt

%%%% edit out bad points
opt1 = 'ctd_proc'; opt2 = 'rawedit_auto'; get_cropt
[d, h] = mloadq(rawfile,'/');

%automatic edits
[d, comment] = apply_autoedits(d, co);
didedits = 0;
if ~isempty(comment)
    h.comment = [h.comment comment];
    didedits = 1;
end

%reapply hand edits
edfilepat = fullfile(MEXEC_G.MDIRLIST.M_CTD,'editlogs',sprintf('mplxyed_*_ctd_%s_%03d',mcruise,stn));
[d, comment] = apply_guiedits(d, 'scan', edfilepat, [co.redoctm stn]);
if ~isempty(comment)
    h.comment = [h.comment comment];
    didedits = 1;
end

%save as cleaned
if didedits
    if exist(m_add_nc(cleanfile),'file')
        delete(cleanfile)
    end
    mfsave(cleanfile, d, h);
end


%%%%% apply corrections
doneco.oxytau = contains(h.comment, '# datcnv_ox_tau_correction = yes');
doneco.oxy1hyst = contains(h.comment, '# datcnv_ox_hysteresis_correction = yes');
doneco.oxy2hyst = doneco.oxy1hyst;
doneco.alignctd = contains(h.comment, '# alignctd_date');
doneco.celltm = contains(h.comment, '# celltm_date');
opt1 = 'ctd_proc'; opt2 = 'raw_corrs'; get_cropt

%fill in some fields we may be missing
if ~isfield(d, 'statnum')
    d.statnum = repmat(stn, size(d.scan));
end
ddu = ['days since ' num2str(MEXEC_G.MDEFAULT_DATA_TIME_ORIGIN(1)) '-01-01 00:00:00'];
d.dday = m_commontime(d,'time',h,ddu); keyboard
h.fldnam = [h.fldnam 'dday']; h.fldunt = [h.fldunt ddu]; h.fldserial = [h.fldserial ' '];

%pressure offset***


%oxygen recalculation (with alternate temperature sensor). uncommon. 
if co.dooxy1V>0 && isfield(co,'oxy1Vcoefs')
    warning('be cautious with oxygen calculated with alternate temperature sensor')
    t = d.(['temp' num2str(co.dooxy1V)]);
    c = d.(['cond' num2str(co.dooxy1V)]);
    s = gsw_SP_from_C(c,t,d.press);
    d.oxy1 = calculate_oxy_from_V(d.sbeoxyV1, d.time, d.press, t, s, co.oxy1Vcoefs);
    h.comment = [h.comment '\n oxy1 recalculated from sbeoxyV1 using CTD' num2str(co.dooxy1V) ' '];
    doneco.oxy1hyst = 0;
else
    co.dooxy1V = 0;
end
if co.dooxy2V>0 && isfield(co,'oxy2Vcoefs')
    warning('be cautious with oxygen calculated with alternate temperature sensor')
    t = d.(['temp' num2str(co.dooxy2V)]);
    c = d.(['cond' num2str(co.dooxy2V)]);
    s = gsw_SP_from_C(c,t,d.press);
    d.oxy2 = calculate_oxy_from_V(d.sbeoxyV2, d.time, d.press, t, s, co.oxy2Vcoefs);
    h.comment = [h.comment '\n oxy2 recalculated from sbeoxyV2 using CTD' num2str(co.dooxy2V) ' '];
    doneco.oxy2hyst = 0;
end

%oxygen tau and hysteresis, including first reversing default hysteresis if
%required
if ~doneco.oxytau
end
if co.redooxyhyst
    %set up a new structure
    oco.hyst_oxy1 = co.hyst_oxy1; %sensor 1 new params
    oco.hyst_oxy2 = co.hyst_oxy2; %sensor 2 new params
    oco.H_0 = [co.hyst_oxy0.H1 co.hyst_oxy0_H2 co.hyst_oxy0_H3];
    if doneco.oxy1hyst
        %reverse first, then apply new
        oco.hrev_oxy1 = co.hyst_oxy0;
    else
        oco.hrev_oxy1 = [];
    end
    if doneco.oxy2hyst
        oco.hrev_oxy2 = co.hyst_oxy0;
    else
        oco.hrev_oxy2 = [];
    end
    [dnew, hnew] = apply_oxyhyst(d, h, oco);
    fn = fieldnames(dnew);
    for no = 1:length(fn)
        d.(fn{no}) = dnew.(fn{no});
    end
end

%cell thermal mass
if ~doneco.celltm
    d.cond1 = apply_ctd_celltm(d.time, d.temp1, d.cond1);
    d.cond2 = apply_ctd_celltm(d.time, d.temp2, d.cond2);
    h.comment = [h.comment '\n cond corrected for cell thermal mass by ctd_apply_celltm'];
end

%oxygen alignment
if ~doneco.alignctd
    for no = 1:size(oxyvars,1)
        d.(oxyvars{no}) = interp1(d.time, d.(oxyvars{no}), d.time+oxy_align);
    end
    h.comment = [h.comment '\n oxygen shifted by ' num2str(oxy_align) ' s'];
    didedits = 1;
end

% turbidity conversion from turbidity volts
if co.doturbV
    d.turbidity = (d.turbidityV-co.turbVpars(2))*co.turbVpars(1);
    d = rmfield(d,'turbidityV');
    hnew.comment = [hnew.comment '\n turbidity converted from turbidity volts'];
    h.fldnam{strcmp('turbidityV',h.fldnam)} = 'turbidity';
    d = orderfields(d,h.fldnam);
end


%%%%% sensor calibrations %%%%%
opt1 = 'ctd_proc'; opt2 = 'ctd_cals'; get_cropt
if isfield(co, 'calstr') && sum(cell2mat(struct2cell(co.docal)))
    %apply calibrations
    [dcal, hcal] = apply_calibrations(d, h, co.calstr, co.docal, 'q');
    hcal = keep_hvatts(hcal, h);

    %if there were calibrations applied to any variables, save those to
    %24hz file (overwriting uncalibrated versions)
    if ~isempty(hcal.fldnam)
        d = dcal; h = hcal;
        mfsave(otfile24, d, h, '-addvars');
    end

else
    %just save to 24 hz file
    mfsave(ctdfile24, d, h);

end

%%%%% check and warn
opt1 = 'ctd_proc'; opt2 = 'cast_divide'; get_cropt
if exist(dcsfile,'file')
    [ddc,~] = mload(dcsfile,'/');
    m = d.scan>=ddc.scan_start & d.scan<=ddc.scan_end;
else
    m = true(size(d.scan));
end
if min(d.press(m))<=-10 && (~isfield(co,'badpress') || ((isfield(co,'badtemp1') || isfield(co,'badtemp2'))))
    msg = {['negative pressures <-10 in ' rawfile ' may be a problem for GSW functions.']};
    if ~co.redoctm
        msg = [msg;
            'check d.press; if there are large spikes also affecting temperature, Ctrl-C'
            'here, edit ctd_proc, redoctm case in opt_' mcruise ', and reprocess this station from _noctm; otherwise,'];
    end
    msg = [msg;
        'you may want to edit ctd_proc, rawedit_auto case of opt_' mcruise ' to remove large'
        'outlier values in pressure (and other variables) before the mctd_rawedit gui stage.'
        'Enter to continue.'];
    fprintf(1,'%s\n',msg{:})
    pause
end
