function [udirs, udcruise] = m_udirs()

udcruise = 'sd025';
udirs = {
'attimu'    'nav/imu'    'sd025_attitude_smc_imu108_2_psmcv';
'attphins'    'nav/phins'    'sd025_attitude_ixblue_phins_surface_motion_kmatt';
'attsea1'    'nav/sea'    'sd025_attitude_seapath_320_1_motion_kmatt';
'attsea2'    'nav/sea'    'sd025_attitude_seapath_320_2_motion_kmatt';
'hdtgryo1'    'nav/gryo'    'sd025_gyrocompass_raytheon_standard_30_mf_1_hehdt';
'hdtgyro2'    'nav/gyro'    'sd025_gyrocompass_raytheon_standard_30_mf_2_hehdt';
'hdtgyrosaf'    'nav/gyrosaf'    'sd025_gyrocompass_safran_bluenaute_hehdt';
'hdtphins'    'nav/phins'    'sd025_attitude_ixblue_phins_surface_heading_hehdt';
'hdtsea1'    'nav/sea'    'sd025_attitude_seapath_320_1_heading_inhdt';
'hdtsea2'    'nav/sea'    'sd025_attitude_seapath_320_2_heading_inhdt';
'possaab'    'nav/saab'    'sd025_gnss_saab_r5_supreme_gngll';
'possea1'    'nav/sea'    'sd025_gnss_seapath_320_1_ingga';
'possea2'    'nav/sea'    'sd025_gnss_seapath_320_2_ingga';
'prsvai1'    'met/vai'    'sd025_met_vaisala_ptb330_n2410065_pvbar';
'prsvai2'    'met/vai'    'sd025_met_vaisala_ptb330_n2410066_pvbar';
'radhei1'    'met/hei'    'sd025_radiometer_heitronics_ct15_85_13316_phsst';
'radhei2'    'met/hei'    'sd025_radiometer_heitronics_ct15_85_13317_phsst';
'radsat1'    'met/sat'    'sd025_radiometer_satlantic_par_ser_icsa_2039_pspar';
'radsat2'    'met/sat'    'sd025_radiometer_satlantic_par_ser_icsa_2040_pspar';
'rotgyro1'    'nav/gyro'    'sd025_gyrocompass_raytheon_standard_30_mf_1_herot';
'rotgyro2'    'nav/gyro'    'sd025_gyrocompass_raytheon_standard_30_mf_2_herot';
'rotgyrosaf'    'nav/gyrosaf'    'sd025_gyrocompass_safran_bluenaute_herot';
'singleb'    'bathy/singleb'    'sd025_singlebeam_kongsberg_ea640_dbdbt';
'singlebskip'    'bathy/singleb'    'sd025_singlebeam_skipper_gds102_sddbt';
'vtgfugro'    'nav/fugro'    'sd025_gnss_fugro_oceanstar_gpvtg';
'vtgsaab'    'nav/saab'    'sd025_gnss_saab_r5_supreme_gnvtg';
'vtgsea1'    'nav/sea'    'sd025_gnss_seapath_320_1_invtg';
'vtgsea2'    'nav/sea'    'sd025_gnss_seapath_320_2_invtg';
'windft'    'met/ft'    'sd025_anemometer_ft_technologies_ft702lt_wimwv';
'windomc1'    'met/omc'    'sd025_anemometer_observator_omc116_1_wimwv';
'windomc2'    'met/omc'    'sd025_anemometer_observator_omc116_2_wimwv';
'windsonic1'    'met/sonic'    'sd025_anemometer_metek_usonic3_1_pmwind';
'windsonic2'    'met/sonic'    'sd025_anemometer_metek_usonic3_2_pmwind';
'windsonic3'    'met/sonic'    'sd025_anemometer_metek_usonic3_3_pmwind';
};
